# Copyright (c) 2023-2024 Antmicro <www.antmicro.com>
# SPDX-License-Identifier: Apache-2.0

ips:
  ip_ibuf:
    file: ipcores/ibuf.yaml
  ip_obuf:
    file: ipcores/obuf.yaml
  ip_iobuf:
    file: ipcores/iobuf.yaml

design:
  name: project_top
  ports:
    ip_obuf:
      clk: PORT_CLK
      rst: PORT_RST
      oe: PORT_CLK
      a: PORT_IN
      z: PORT_OUT_0
    ip_iobuf:
      clk: PORT_CLK
      rst: PORT_RST
      oe: PORT_CLK
      a: PORT_IN
      y: PORT_OUT_1
    ip_ibuf:
      clk: PORT_CLK
      rst: PORT_RST
      a: PORT_IN
      z: PORT_OUT_2

external:
  ports:
    in:
      - PORT_CLK
      - PORT_RST
      - PORT_IN
    out:
      - PORT_OUT_0
      - PORT_OUT_1
      - PORT_OUT_2
    inout:
      - [ip_iobuf, z]
