# Copyright (c) 2023-2024 Antmicro <www.antmicro.com>
# SPDX-License-Identifier: Apache-2.0

stages:
  - test
  - build
  - deploy

image: debian:bookworm

lint:
  stage: test
  before_script: &BeforeScript
    - apt-get update -qq
    - apt-get install -y --no-install-recommends python3-pip python3-venv
    - python3 -m venv venv
    - source venv/bin/activate
    - python3 -m pip install -U pip wheel setuptools
  script:
    - python3 -m pip install -r requirements.txt
    - nox -s isort_check black_check flake8

pytest:
  stage: test
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  before_script:
    - apt-get update -qq
    - apt-get install -y --no-install-recommends wget git python3-dev python3-venv make ninja-build gcc-riscv64-unknown-elf bsdextrautils verilator
    - mkdir -p miniconda3
    - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda3/miniconda.sh
    - bash miniconda3/miniconda.sh -b -u -p miniconda3
    - rm -rf miniconda3/miniconda.sh
    - source miniconda3/bin/activate
    - conda create -n venv python=3.9
    - conda activate venv
    - conda install -c conda-forge gcc=12.1.0
  script:
    - apt-get install -y --no-install-recommends git python3-dev
    - python3 -m pip install nox
    - python3 -m pip install git+https://github.com/antmicro/tuttest
    - tuttest README.md | bash -
    - nox -s tests_with_report
  artifacts:
    paths:
      - cov_html

docs-verify:
  stage: test
  script:
    - eval ${VERIFY_SCRIPT}

docs-build:
  image: $CI_DOCS_DOCKER_IMAGE
  stage: build
  tags: ['ace-x86_64']
  before_script:
    - pip3 install -r docs/requirements.txt
  script:
    - cd docs
    - echo -en "\nhtml_js_files = [ '$ANNOTANT' ]" >> source/conf.py
    - make html latexpdf
    - cp build/latex/*.pdf build/html/
    - cp -r ../cov_html build/html/cov
    - tar cf ../$CI_DOCS_ARCHIVE -C build/html/ .
  artifacts:
    paths:
      - docs/build
      - $CI_DOCS_ARCHIVE

docs-deploy:
  variables:
    GIT_STRATEGY: none
  dependencies: [ docs-build ]
  stage: deploy
  tags: ['docs']
  script: echo 'Deploying docs'
  artifacts:
    paths:
      - $CI_DOCS_ARCHIVE
