# Copyright (c) 2023-2024 Antmicro <www.antmicro.com>
# SPDX-License-Identifier: Apache-2.0

stages:
  - test
  - build_docs
  - deploy_docs

variables:
  DEBIAN_FRONTEND: noninteractive

lint:
  stage: test
  tags: ['ace-x86_64']
  image: debian:bookworm
  script:
    - ./.github/scripts/test.sh lint

examples:
  stage: test
  tags: ['ace-x86_64']
  image: debian:bookworm
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  script:
    - ./.github/scripts/test.sh examples

tests:
  stage: test
  tags: ['ace-x86_64']
  image: debian:bookworm
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  script:
    - ./.github/scripts/test.sh tests

include:
  - project: 'repositories/topwrap'
    ref: internal_ci_yaml
    file: '/internal.yml'

build_docs:
  image: $CI_DOCS_DOCKER_IMAGE
  stage: build_docs
  tags: ['ace-x86_64']
  before_script:
    - pip3 install -r docs/requirements.txt
  script:
    - cd docs
    - echo -en "\nhtml_js_files = [ '$ANNOTANT' ]" >> source/conf.py
    - make html latexpdf
    - cp build/latex/*.pdf build/html/
    - tar cf ../$CI_DOCS_ARCHIVE -C build/html/ .
  artifacts:
    paths:
      - docs/build
      - $CI_DOCS_ARCHIVE

deploy_docs:
  image: $CI_DOCS_DOCKER_IMAGE
  variables:
    GIT_STRATEGY: none
  dependencies:
    - build_docs
  stage: deploy_docs
  tags: ['docs']
  script: echo 'Deploying docs'
  artifacts:
    paths:
      - $CI_DOCS_ARCHIVE

