# Copyright (c) 2023-2024 Antmicro <www.antmicro.com>
# SPDX-License-Identifier: Apache-2.0

stages:
  - test
  - examples
  - build_docs
  - deploy_docs

variables:
  DEBIAN_FRONTEND: noninteractive

lint:
  stage: test
  tags: ['ace-x86_64']
  image: debian:bookworm
  before_script:
    - apt-get update -qq
    - apt-get install -y --no-install-recommends
        git
        python3-pip
        python3-venv
    - python3 -m venv venv
    - source venv/bin/activate
    - python3 -m pip install -U pip wheel setuptools
  script:
    - pip install ".[lint]"
    - nox -s isort_check black_check flake8

.generate_example:
  stage: examples
  tags: ['ace-x86_64']
  image: debian:bookworm
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  before_script:
    - apt-get update -qq
    - apt-get install -y --no-install-recommends
        git
        python3-dev
        python3-venv
        python3-pip
    - python3 -m venv venv
    - source venv/bin/activate
    - python3 -m pip install git+https://github.com/antmicro/tuttest
    - tuttest README.md | bash -
  script:
    - cd examples/$EXAMPLE
    - tuttest README.md install-deps,generate | bash -

tests:
  stage: test
  tags: ['ace-x86_64']
  image: debian:bookworm
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  before_script:
    - apt-get update -qq
    - apt-get install -y --no-install-recommends
        curl
        wget
        git
        python3-dev
        python3-venv
        python3-pip
        make
        meson
        ninja-build
        gcc-riscv64-unknown-elf
        bsdextrautils
        verilator
        libssl-dev
        libreadline-dev
        libffi-dev
        libbz2-dev
        libncurses-dev
        libsqlite3-dev
        liblzma-dev
    - python3 -m venv venv
    - source venv/bin/activate
    - python3 -m pip install nox
    - python3 -m pip install git+https://github.com/antmicro/tuttest
    - tuttest README.md | bash -
  script:
    - nox -s tests_with_reports_in_env

example_hdmi:
  extends: .generate_example
  variables:
    EXAMPLE: hdmi

example_inout:
  extends: .generate_example
  variables:
    EXAMPLE: inout

example_pwm:
  extends: .generate_example
  variables:
    EXAMPLE: pwm

include:
  - project: 'repositories/topwrap'
    ref: internal_ci_yaml
    file: '/internal.yml'

build_docs:
  image: $CI_DOCS_DOCKER_IMAGE
  stage: build_docs
  tags: ['ace-x86_64']
  before_script:
    - pip3 install -r docs/requirements.txt
  script:
    - cd docs
    - echo -en "\nhtml_js_files = [ '$ANNOTANT' ]" >> source/conf.py
    - make html latexpdf
    - cp build/latex/*.pdf build/html/
    - tar cf ../$CI_DOCS_ARCHIVE -C build/html/ .
  artifacts:
    paths:
      - docs/build
      - $CI_DOCS_ARCHIVE

deploy_docs:
  image: $CI_DOCS_DOCKER_IMAGE
  variables:
    GIT_STRATEGY: none
  dependencies:
    - build_docs
  stage: deploy_docs
  tags: ['docs']
  script: echo 'Deploying docs'
  artifacts:
    paths:
      - $CI_DOCS_ARCHIVE

