# Copyright (c) 2023-2024 Antmicro <www.antmicro.com>
# SPDX-License-Identifier: Apache-2.0

stages:
  - test
  - build_docs
  - deploy_docs

variables:
  DEBIAN_FRONTEND: noninteractive
  SCALENODE_RAM: 12288
  SCALENODE_CPU: 6

lint:
  stage: test
  image: debian:bookworm
  script:
    - ./.github/scripts/ci.sh lint

tests:
  stage: test
  image: debian:bookworm
  script:
    - ./.github/scripts/ci.sh tests

package_test:
  stage: test
  image: debian:bookworm
  script:
    - ./.github/scripts/ci.sh package_dist

examples:
  stage: test
  image: debian:bookworm
  script:
    - ./.github/scripts/ci.sh examples
  artifacts:
    paths:
      - examples/**/build

package_cores:
  stage: test
  image: debian:bookworm
  script:
    - ./.github/scripts/ci.sh package_cores
  artifacts:
    paths:
      - core_repo/**

build_docs:
  image: $CI_DOCS_DOCKER_IMAGE
  stage: build_docs
  script:
    - ./.github/scripts/ci.sh docs
    - tar cf "$CI_DOCS_ARCHIVE" -C docs/build/html/ .
  artifacts:
    paths:
      - docs/build
      - $CI_DOCS_ARCHIVE

deploy_docs:
  image: $CI_DOCS_DOCKER_IMAGE
  variables:
    GIT_STRATEGY: none
  dependencies: [ build_docs ]
  stage: deploy_docs
  tags: ['docs']
  script: echo 'Deploying docs'
  artifacts:
    paths:
      - $CI_DOCS_ARCHIVE

include:
  - project: 'repositories/topwrap'
    ref: internal_ci_yaml
    file: '/internal.yml'
