stages:
  - test
  - build
  - deploy

image: debian:bullseye

lint:
  stage: test
  before_script: &BeforeScript
    - apt-get update -qq
    - apt-get install -y --no-install-recommends python3-pip
    - python3 -m pip install -U pip wheel setuptools
  script:
    - python3 -m pip install -r requirements.dev.txt
    - nox -s isort black flake8

pytest:
  stage: test
  before_script: *BeforeScript
  script:
    - apt-get install -y --no-install-recommends g++ make git python3-dev
    - python3 -m pip install -r requirements.dev.txt
    - python3 -m pip install git+https://github.com/antmicro/tuttest
    - tuttest README.md | bash -
    - nox -s tests

docs-verify:
  stage: test
  script:
    - eval ${VERIFY_SCRIPT}

docs-build:
  image: $CI_DOCS_DOCKER_IMAGE
  stage: build
  tags: ['ace-x86_64']
  before_script:
    - pip3 install -r docs/requirements.txt
  script:
    - cd docs
    - echo -en "\nhtml_js_files = [ '$ANNOTANT' ]" >> source/conf.py
    - make html latexpdf
    - cp build/latex/*.pdf build/html/
    - tar cf ../$CI_DOCS_ARCHIVE -C build/html/ .
  artifacts:
    paths:
      - docs/build
      - $CI_DOCS_ARCHIVE

docs-deploy:
  variables:
    GIT_STRATEGY: none
  dependencies: [ docs-build ]
  stage: deploy
  tags: ['docs']
  script: echo 'Deploying docs'
  artifacts:
    paths:
      - $CI_DOCS_ARCHIVE
