name: Pipeline


on: [pull_request, push, workflow_dispatch]


jobs:


  Tests:

    runs-on: ubuntu-latest
    name: "Test Python ${{ matrix.python-version }}"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dev requirements
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y \
            antlr4 \
            libantlr4-runtime-dev \
            python3-dev \
            yosys
          python3 -m pip install --upgrade pip wheel setuptools
          python3 -m pip install -r requirements.dev.txt
          python3 -m pip install git+https://github.com/antmicro/tuttest

      - name: Run lint checks
        run: nox -s isort black flake8

      - name: Build
        run: tuttest README.md | bash -

      - name: Run pytest with nox
        run: nox -s tests


  Examples:

    runs-on: ubuntu-latest
    name: 'Example ${{ matrix.example }}'
    strategy:
      fail-fast: false
      matrix:
        example:
          - HDMI
          - INOUT
          - PWM

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install tuttest and fpga-topwrap
        run: |
          python3 -m pip install git+https://github.com/antmicro/tuttest
          tuttest README.md | bash -

      - name: Generate sources for example HDMI setup
        if: matrix.example == 'HDMI'
        run: |
          cd examples/hdmi
          tuttest README.md generate | bash -
          cd -

      - name: Generate sources for example inout setup
        if: matrix.example == 'INOUT'
        run: |
          cd examples/inout
          tuttest README.md generate | bash -
          cd -

      - name: Generate sources for and build example PWM setup
        if: matrix.example == 'PWM'
        run: |
          cd examples/pwm
          tuttest README.md generate | bash -
          cd -

      - uses: actions/upload-artifact@v3
        if: matrix.example == 'PWM'
        with:
          name: top.bit
          path: top.bit
