# Copyright (c) 2023-2024 Antmicro <www.antmicro.com>
# SPDX-License-Identifier: Apache-2.0

name: Pipeline

on: [pull_request, push, workflow_dispatch]

defaults:
  run:
    shell: bash

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
    name: "Run lint checks"

    steps:
      - name: Install git package
        run: |
          apt-get update -qq
          apt-get install -y git

      - uses: actions/checkout@v4

      - name: Run lint checks
        run: |
          ./.github/scripts/ci.sh lint

  tests:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
    name: "Run tests"

    steps:
      - name: Install git package
        run: |
          apt-get update -qq
          apt-get install -y git

      - uses: actions/checkout@v4

      - name: Run Python tests
        run: |
          ./.github/scripts/ci.sh tests

  examples:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
    name: 'Generate examples'

    steps:
      - name: Install git package
        run: |
          apt-get update -qq
          apt-get install -y git

      - uses: actions/checkout@v4

      - name: Generate Topwrap examples
        run: |
          ./.github/scripts/ci.sh examples

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: examples
          path: examples/**/build
